# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7b2a523c1bfec4c0e0ebecb2198aeb10c8fc3ed1eee52a73a4136485fe78c0535e4c7a7ff67b496da001bff30663229339fbfc25a8d4901e3994df745ed0818

test:
  secret_key_base: cd226a22df98c7acc619fda45fc5eea6424b29a77d86ec83bf8a2200c75ed96cc2c1617a1f37a6bcc6c2a13a3aba74d012fc5e60aec94de2ceaa1ff87867b48d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
